config/dtb: samsung-e7: Add panel driver
msm8916-mainline/linux-panel-drivers pull request #9
Opened 2022-01-04 14:56 UTC by wonderfulShrineMaidenOfParadise

2022-02-08 13:37 UTC, wonderfulShrineMaidenOfParadise commented
Tested `ea8601` driver on `ea8061-id400418`. The display looks green but basically works.

2022-03-02 09:47 UTC, stephan-gh approved these changes

2022-03-02 10:16 UTC, stephan-gh requested changes

2022-03-02 11:10 UTC, stephan-gh approved these changes

2022-03-02 17:20 UTC, TravMurav approved these changes

2022-03-03 10:56 UTC, stephan-gh commented
Pushed, thanks!

2022-03-03 10:56 UTC, closed without merging